## path to tools
samTools:  /fh/fast/ha_g/app/tools/conda/bin/samtools
bcfTools:  /app/easybuild/software/BCFtools/1.9-foss-2016b/bin/bcftools
svaba_exe:  /fh/fast/ha_g/app/bin/svaba

## path to scripts ##
readCounterScript:  /fh/fast/ha_g/app/bin/readCounter
ichorCNA_rscript:  /fh/fast/ha_g/user/mko/ichorCNA/scripts/runIchorCNA.R
pyCountScript:  code/countPysam.py
TitanCNA_rscript: /fh/fast/ha_g/user/mko/TitanCNA/scripts/R_scripts/titanCNA.R
TitanCNA_combineTitanIchorCNA:  code/combineTITAN-ichor.R
TitanCNA_selectSolutionRscript: /fh/fast/ha_g/user/mko/TitanCNA/scripts/R_scripts/selectSolution.R
TitanCNA_libdir:  /fh/fast/ha_g/user/mko/TitanCNA
ichorCNA_libdir:  /fh/fast/ha_g/user/mko/ichorCNA # include if ichorCNA R source files changed but package has not been updated within R

## path to scripts ##
svaba_funcs:  code/svaba_utils.R
plot_funcs:  code/plotting.R
combineSVCN_script:  code/combineSVABAandTITAN.R
plotSVCN_script:  code/plotTitanSvaba.R
plotSVCNichor_script: code/plotIchorSvaba.R
plotCircos_script: code/create_circosPlot.R

## reference settings and paths to reference files ##
genomeBuild: hg38
genomeStyle: UCSC
refFasta:  /fh/fast/ha_g/grp/reference/GRCh38/10XG/refdata-GRCh38-2.1.0/fasta/genome.fa
snpVCF:  /fh/fast/ha_g/grp/reference/GRCh38/hapmap_3.3.hg38.vcf.gz
cytobandFile:  /fh/fast/ha_g/user/mko/ichorCNA/inst/extdata/cytoBand_hg38.txt # only need if hg38
centromere:  /fh/fast/ha_g/user/mko/ichorCNA/inst/extdata/GRCh38.GCA_000001405.2_centromere_acen.txt
sex:  male   # use None if both females and males are in sample set

## params for each step ##

## read depth params ##
# use this for NCBI chr naming
#chrs: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X,Y 
# use this for UCSC chr naming
chrs: chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrY 
binSize:  10000

## getAllelCounts params
map_quality:  10
base_quality: 10
vcf_quality:  100

## ichorCNA params
# use panel matching same bin size (optional)
# ichorCNA_normalPanel: ../../inst/extdata/HD_ULP_PoN_hg38_1Mb_median_normAutosome_median.rds
# must use gc wig file corresponding to same binSize (required)
ichorCNA_exons: NULL
ichorCNA_gcWig: /fh/fast/ha_g/user/mko/ichorCNA/inst/extdata/gc_hg38_10kb.wig
# must use map wig file corresponding to same binSize (required)
ichorCNA_mapWig:  /fh/fast/ha_g/user/mko/ichorCNA/inst/extdata/map_hg38_10kb.wig
# use bed file if sample has targeted regions, eg. exome data (optional)
ichorCNA_repTimeWig: /fh/fast/ha_g/user/mko/ichorCNA/inst/extdata/RepTiming_hg38_10kb.wig
ichorCNA_centromere:  /fh/fast/ha_g/user/mko/ichorCNA/inst/extdata/GRCh38.GCA_000001405.2_centromere_acen.txt

ichorCNA_chrs:  paste0('chr', c(1:22, \"X\"))
ichorCNA_genomeBuild: hg38
ichorCNA_genomeStyle:  UCSC

# chrs used for training ichorCNA parameters, e.g. tumor fraction. 
ichorCNA_chrTrain:  paste0('chr', c(1:22))
# non-tumor fraction parameter restart values; higher values should be included for cfDNA
ichorCNA_normal:  c(0.5)
# ploidy parameter restart values
ichorCNA_ploidy:  c(2,3,4)
ichorCNA_estimateNormal:  TRUE
ichorCNA_estimatePloidy:  TRUE
ichorCNA_estimateClonality: TRUE
# states to use for subclonal CN
ichorCNA_scStates:  c(1,3)
# set maximum copy number to use
ichorCNA_maxCN:  8
# TRUE/FALSE to include homozygous deletion state
ichorCNA_includeHOMD: TRUE
# control segmentation - higher (e.g. 0.9999999) leads to higher specificity and fewer segments
ichorCNA_minMapScore: 0.75
ichorCNA_maxFracGenomeSubclone: 0.5
ichorCNA_maxFracCNASubclone: 0.7
# lower (e.g. 0.99) leads to higher sensitivity and more segments
ichorCNA_txnE:  0.9999
# control segmentation - higher (e.g. 10000000) leads to higher specificity and fewer segments
# lower (e.g. 100) leads to higher sensitivity and more segments
ichorCNA_txnStrength:  10000
ichorCNA_plotFileType:  pdf
ichorCNA_plotYlim:  c(-2,4)

## TitanCNA params
TitanCNA_maxNumClonalClusters: 3
TitanCNA_chrs:  c(1:22, \"X\")
TitanCNA_normalInit: 0.5
TitanCNA_maxPloidy: 4
TitanCNA_estimateNormal:  map
TitanCNA_estimatePloidy:  TRUE
TitanCNA_estimateClonality: TRUE
TitanCNA_alleleModel: binomial
TitanCNA_alphaK:  10000
TitanCNA_alphaR:  10000
TitanCNA_txnExpLen: 1e15
TitanCNA_plotYlim:  c(-2,4)
TitanCNA_solutionThreshold: 0.05
TitanCNA_numCores: 1

## SVABA settings ##
svaba_dbSNPindelVCF:  /fh/fast/ha_g/grp/reference/GRCh38/known_polymorphic_sites/resources_broad_hg38_v0_Homo_sapiens_assembly38.known_indels.vcf.gz
svaba_minSPAN:  10000
svaba_minInversionSPAN: 1000
svaba_numThreads: 4 #make sure this is okay

##Svaba Plotting parameters ##
plot_zoom:  FALSE
plot_chrs:  c(1:22, \"X\") # "None" will also plot all chromosomes
plot_startPos:  None
plot_endPos:  None
plot_geneFile:  data/gene_list_72.txt ## include list of genes to annotate on plot
plot_ylim:  c(-2,4)
plot_size:  c(8,4)
plot_type:  titan ## titan - will include haplotype fraction
plot_format:  png
plot_ichor_units: logratio


