samples: #format is sample_name: /path/to/sample.bam for both tumors and normals
  001_Tumor:  001_Tumor.bam
  001_Normal:  001_Normal.bam


pairings: #format is tumor: matched_normal
  001_Tumor: 001_Normal
