samples: #format is sample_name: /path/to/sample.bam for both tumors and normals
  01-006-T:  /path/to/01-006-T_tumor.bam
  01-006-N:  /path/to/01-006-N_normal.bam


pairings: #format is tumor: matched_normal
  01-006-T: 01-006-N
